name: "playstation-box"
description: "Update a pinned gist to contain PlayStation stats"
branding:
  icon: "flag"
  color: "yellow"
runs:
  using: 'composite'
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: Install Dependencies
      shell: bash
      run: uv sync
    - name: Run
      shell: bash
      run: uv run python src/main.py
